export const PLANNING_SESSION_LIFETIME_DAYS = 7;

export const PLANNING_SESSION_LIFETIME_MS =
  PLANNING_SESSION_LIFETIME_DAYS * 24 * 60 * 60 * 1000;

export const PLANNING_SESSION_STORAGE_KEY =
  "potato-trips:planning-session-id";

export const PLANNING_SESSION_PROMPT_MAX_LENGTH = 2000;
export const PLANNING_SESSION_MESSAGE_MAX_LENGTH = 2000;
export const PLANNING_SESSION_MAX_ASSISTANT_TURNS = 12;
export const PLANNING_SESSION_MAX_CONFIRMATION_REVISION_AI_TURNS = 3;
export const PLANNING_SESSION_MAX_GENERATION_ATTEMPTS = 3;
export const PLANNING_SESSION_GENERATION_QUEUE_NAME =
  "planning-session-generation";
export const PLANNING_SESSION_STALE_PREPARING_TRIP_MS = 7 * 60 * 1000;
export const PLANNING_SESSION_STALE_ACTIVE_GENERATION_MS = 70 * 60 * 1000;
export const PLANNING_SESSION_STALE_GENERATION_ERROR_MESSAGE =
  "Generation timed out while waiting for background processing. Please retry.";
export const PLANNING_SESSION_PLACE_RESOLUTION_MAX_REQUESTS = 60;
export const PLANNING_SESSION_PLACE_RESOLUTION_CONCURRENCY = 5;
export const PLANNING_SESSION_PLACE_COORDINATES_TTL_DAYS = 30;

export const PLANNING_SESSION_ID_MAX_LENGTH = 255;
